### PR TITLE
Changing mqtt client library to paho-mqtt

### PR DESCRIPTION
**Pull request by lwalter86**

### CODE REVIEW

**Comment by scls19fr** [comment]
https://travis-ci.org/scls19fr/numpy-buffer/jobs/442193411#L466

**Comment by lwalter86** [comment]
I didn't have this error on local flake8 check ...

**Comment by scls19fr** [comment]
Maybe we should compare `flake8 --version`

https://travis-ci.org/scls19fr/numpy-buffer/jobs/442193411#L461

**Comment by scls19fr** [comment]
But that's fixed here so I'm merging now.
Thanks again @lwalter86

**Pull request merged**
